[package]
name = "axim"
version = "0.0.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
data-encoding = "2.3.2"
libc = "0.2.86"
nix = "0.20.0"
sha3 = "0.9.1"
